### PR TITLE
Update AVS and ASN acronyms 3-plan-network-topology.md

### PR DESCRIPTION
**Pull request by suzuber**
Spelled out AVS, can't use acronym. Introduced Autonomous System Number (ASN) before using the acronym.

Before requesting or performing a merge in upstream:

- [x] Verify that your pull request is following our PR quality criteria (items that apply to All and Learn):
       https://review.learn.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=main
- [x] Verify your PR has a useful title that reflects what it is for.

### CODE REVIEW

**Comment by suzuber** [comment]
#sign-off

**Comment by suzuber** [comment]
@pdets please review this PR, thank you.

**Comment by suzuber** [comment]
@pdets please review this PR, thank you.

**Comment by suzuber** [comment]
@pdetspublish

**Comment by tynevi** [comment]
As noted in the Readme, we don't accept pull requests into this repository. If you would like to submit feedback about learning content, please use the feedback link on the page on learn.microsoft.com.

**Pull request closed without merging**
